# Change these first
owner: vandie # Your GitHub username
repo: bartop-uptime # Your Github repository name

# Add your sites here
sites:
  - name: App Servers
    url: https://app.bartop.xyz
  - name: API Servers
    url: $API_SERVER
  - name: API Database
    url: $DATABASE_URL
    headers: 
      - "Authorization: Bearer $API_TOKEN"
  - name: Dashboard Systems
    url: https://bartop.xyz

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.bartop.xyz
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://https://app.bartop.xyz/assets/loader.svg
  name: BartopXYZ
  introTitle: "**BartopXYZ** is a cocktail and drink lookup service that works using the drink in your bar."
  introMessage: This page allows you to see the uptime of our various systems and will report any issues that may be occuring at this point in time.
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
