# Change these first
owner: BartopXYZ # Your GitHub username
repo: uptime # Your Github repository name

# Add your sites here
sites:
  - name: PWA & App Systems
    url: https://app.bartop.xyz
  - name: API
    url: $API_SERVER
  - name: Database
    url: $DATABASE_URL
    headers: 
      - "Authorization: Bearer $API_TOKEN"
  - name: Dashboard Systems
    url: https://bartop.xyz

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.bartop.xyz
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://app.bartop.xyz/assets/loader.svg
  name: BartopXYZ Uptime
  introTitle: "**BartopXYZ** is a cocktail and drink lookup app that recomends drinks you can atually make"
  introMessage: This page allows you to see the uptime of our various systems and will report any issues that may be occuring that could stop you from enjoying our content.
  navbar:
    - title: Status
      href: /

      # Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
